version: "3"
services:
  bazaarex:
    container_name: bazaarex
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3200:3000
    volumes:
      - .:/app:rw
      - /app/node_modules
    environment:
      GENERATE_SOURCEMAP: false
      API_URL: "https://api.orderly.org/v1/public"
    command: sh -c "yarn install && yarn build && yarn start"
