ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@reown/appkit'
  - '@stellar/stellar-sdk'
  - bigint-buffer
  - blake-hash
  - bufferutil
  - es5-ext
  - esbuild
  - keccak
  - protobufjs
  - secp256k1
  - sharp
  - tiny-secp256k1
  - unrs-resolver
  - usb
  - utf-8-validate
